### ISSUE TITLE
Location ID应该也可以识别字符串类型

### ISSUE THREAD

**Issue by h-mole** [Jack0Chan/PyUPPAAL#34]
经过测试，UPPAAL也可以识别字符串类型的Location.id。但如果直接用字符串类型的文件输入，可能出现问题。

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/SkyPlatformPyTool/run.py", line 311, in _inner
    d = f(exec_ctx_wrapper, args)
  File "/root/app/app.py", line 96, in handler
    self.compose_model(model_file_local, config,
  File "/root/app/app.py", line 55, in compose_model
    umodel = pyuppaal.UModel(input_model_path)
  File "/usr/local/lib/python3.10/dist-packages/pyuppaal/umodel.py", line 50, in __init__
    self.__build()
  File "/usr/local/lib/python3.10/dist-packages/pyuppaal/umodel.py", line 250, in __build
    self.__templates = [Template.from_xml(t) for t in template_elems]
  File "/usr/local/lib/python3.10/dist-packages/pyuppaal/umodel.py", line 250, in <listcomp>
    self.__templates = [Template.from_xml(t) for t in template_elems]
  File "/usr/local/lib/python3.10/dist-packages/pyuppaal/nta.py", line 757, in from_xml
    locations.append(Location.from_xml(l_elem))
  File "/usr/local/lib/python3.10/dist-packages/pyuppaal/nta.py", line 257, in from_xml
    res = Location(location_id=int(root.get("id")[2:]),
ValueError: invalid literal for int() with base 10: 'SEC_wait'
```

**Comment by Jack0Chan** [comment]
通常来说，Location ID是由UPPAAL自动设置的，为int格式，在UPPAAL的ide中没有找到能够修改Location id的地方。
1. 请问什么情况下会手动指定location id呢？您是否在更新Location的Name？
2. 如果确实需要location id为字符串，能否麻烦提供一个测试用例，方便我们更新？
